print("A")
name = input("Please Enter your name: ")
print(--------------------------------")
address = input("Please enter you post code: ")
print("B")
print("-------------------------------")
print(name,address)